export const ALL_TOPICS_REQUEST = "ALL_TOPICS_REQUEST";
export const ALL_TOPICS_SUCCESS = "ALL_TOPICS_SUCCESS";
export const ALL_TOPICS_FAIL = "ALL_TOPICS_FAIL";

export const CREATE_TOPIC_REQUEST = "CREATE_TOPIC_REQUEST";
export const CREATE_TOPIC_SUCCESS = "CREATE_TOPIC_SUCCESS";
export const CREATE_TOPIC_RESET = "CREATE_TOPIC_RESET";
export const CREATE_TOPIC_FAIL = "CREATE_TOPIC_FAIL";

export const UPDATE_TOPIC_REQUEST = "UPDATE_TOPIC_REQUEST";
export const UPDATE_TOPIC_SUCCESS = "UPDATE_TOPIC_SUCCESS";
export const UPDATE_TOPIC_RESET = "UPDATE_TOPIC_RESET";
export const UPDATE_TOPIC_FAIL = "UPDATE_TOPIC_FAIL";

export const DELETE_TOPIC_REQUEST = "DELETE_TOPIC_REQUEST";
export const DELETE_TOPIC_SUCCESS = "DELETE_TOPIC_SUCCESS";
export const DELETE_TOPIC_RESET = "DELETE_TOPIC_RESET";
export const DELETE_TOPIC_FAIL = "DELETE_TOPIC_FAIL";

export const TOPIC_DETAILS_REQUEST = "TOPIC_DETAILS_REQUEST";
export const TOPIC_DETAILS_SUCCESS = "TOPIC_DETAILS_SUCCESS";
export const TOPIC_DETAILS_FAIL = "TOPIC_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";